version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Uncomment if you need environment variables
    # env_file:
    #   - .env.production
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
